# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v4

      - name: Install Swift
        uses: slashmo/install-swift@v0.1.0
        with:
          version: 5.9.0

      - name: Get swift version
        run: swift --version

      - name: Install dependencies
        run: swift package update

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
